services:
    avro_case.converter:
        class: Avro\CaseBundle\Util\CaseConverter

    avro_case.twig.extension:
        class: Avro\CaseBundle\Twig\Extension/CaseExtension
        tags:
            -  { name: twig.extension } 
        arguments: ["@avro_case.converter"]

